### ISSUE TITLE
Informal word 'quitar' is used but with wide impact

### ISSUE THREAD

**Issue by shenhuiying2017** [MicrosoftDocs/azure-docs.es-es#119]
The verb “quitar” is kind of a vulgar word that Spanish would never use in a formal situation as this one because it has a literal meaning of physically taking something out. 
Current translation: La base de datos de destino se ha quitado. // Quite la base de datos de destino e inténtelo de nuevo.// Cree particiones o elimine datos, quite índices o consulte la documentación para obtener soluciones posibles. // quitándolos una vez que la sesión ya no los necesite.
Suggestion translation: La base de datos de destino se ha eliminado. // Elimine la base de datos de destino e inténtelo de nuevo. // Cree particiones o elimine datos, elimine índices o consulte la documentación para obtener soluciones posibles.// eliminándolos una vez que la sesión ya no los necesite.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 48d01116-e0d9-f62d-1f10-3f2e13a2d2f1
* Version Independent ID: e4c42205-428c-8487-265a-173f324e8d66
* Content: [Códigos de error de SQL: error de conexión de base de datos](https://docs.microsoft.com/es-es/azure/sql-database/sql-database-develop-error-messages)
* Content Source: [articles/sql-database/sql-database-develop-error-messages.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/sql-database/sql-database-develop-error-messages.md)
* Service: **sql-database**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by gosali** [comment]
Hello, @shenhuiying2017 , 

 Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 

Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @shenhuiying2017 , 
 
 Thank you for your linguistic feedback.  
  
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because we use delete, remove, clear, etc. with slightly differente meanings and this should be reflected in Spanish, hence, after many deliberations, we decided to use "quitar" as translation of "remove".

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.  
 
Kind regards, 
Microsoft DOCS International Team
