### ISSUE TITLE
Add Visual Studio Code as an alternative for Mac OS or Linux users

### ISSUE THREAD

**Issue by jmarti326** [MicrosoftDocs/azure-docs.es-es#142]
In the "quickstart translator speech api with c#" Visual Studio Code it's a perfect working alternative for those using a computer with Mac OS or Linux.

**Comment by jmarti326** [comment]
Pull Request #143 Solves this problem

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #https://github.com/MicrosoftDocs/azure-docs.es-es/pull/143. For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
