### ISSUE TITLE
Procedure doesn't work for us

### ISSUE THREAD

**Issue by sonfrau** [MicrosoftDocs/azure-docs.es-es#147]
We followed this procedure, step by step but it didn't work for us.

We had to add this line:

ad_gpo_access_control = permissive

to our sssd.conf and as of then we were able to gain access to our linux servers using AAD credentials.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ffffb136-b73f-2b2a-728d-b4c57f08ee5b
* Version Independent ID: 9a7bac18-2601-1a24-21b3-0f3134277ed6
* Content: [Azure Active Directory Domain Services: Unión de una máquina virtual Ubuntu a un dominio administrado](https://docs.microsoft.com/es-es/azure/active-directory-domain-services/active-directory-ds-join-ubuntu-linux-vm)
* Content Source: [articles/active-directory-domain-services/active-directory-ds-join-ubuntu-linux-vm.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory-domain-services/active-directory-ds-join-ubuntu-linux-vm.md)
* Service: **active-directory**
* GitHub Login: @eringreenlee
* Microsoft Alias: **ergreenl**

**Comment by sonfrau** [comment]
I forgot to mention we are using Ubuntu 16.04

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #18906](https://github.com/MicrosoftDocs/azure-docs/issues/18906) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @sonfrau 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/18906.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
