### ISSUE TITLE
URL of Notebook is incorrect

### ISSUE THREAD

**Issue by dpserfaty** [MicrosoftDocs/azure-docs.es-es#340]
Hello! 
The URL to import the notebook in Databricks has a blank space in the middle of it. What could I do? 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 91402667-4be2-ddaf-6b7a-d24d478e5cac
* Version Independent ID: f171700d-f8e1-8b79-779c-9e12c0a03fa8
* Content: [Transformación de datos mediante Databricks en Azure Data Factory](https://docs.microsoft.com/es-es/azure/data-factory/solution-template-databricks-notebook#feedback)
* Content Source: [articles/data-factory/solution-template-databricks-notebook.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/data-factory/solution-template-databricks-notebook.md)
* Service: **data-factory**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #27618](https://github.com/MicrosoftDocs/azure-docs/issues/27618) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @dpserfaty 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/27618

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
