### ISSUE TITLE
How to change cluster.local default name

### ISSUE THREAD

**Issue by evmimagina** [MicrosoftDocs/azure-docs.es-es#691]
Hi,

Is there any way to use the coredns-custom feature to change the cluster.local default name?

Thanks,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2f95537e-770a-739c-0175-4447a995f8b2
* Version Independent ID: 6c9a1132-05af-70f1-5a2b-8dad56de9cc3
* Content: [Personalización de CoreDNS para Azure Kubernetes Service (AKS)](https://docs.microsoft.com/es-es/azure/aks/coredns-custom)
* Content Source: [articles/aks/coredns-custom.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/aks/coredns-custom.md)
* Service: **container-service**
* GitHub Login: @jnoller
* Microsoft Alias: **jenoller**

**Comment by srvbpigh** [comment]
Hello, @evmimagina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/azure-docs #43504](https://github.com/MicrosoftDocs/azure-docs/issues/43504) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
Hello, @evmimagina 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43504.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
