### ISSUE TITLE
improvement content - clean-up-resources section missing

### ISSUE THREAD

**Issue by aitormartinezvalderrama** [MicrosoftDocs/azure-docs.es-es#696]
What about "clean-up-resources" section in this page "https://docs.microsoft.com/es-es/azure/app-service/app-service-web-get-started-dotnet-framework" like in the start guide os .NET Core (https://docs.microsoft.com/es-es/azure/app-service/app-service-web-get-started-dotnet#clean-up-resources). Thanks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b1055184-0535-4318-2ae9-79e37bea0f28
* Version Independent ID: b5dfedf8-c884-138b-0b3d-eea41e64c62b
* Content: [Inicio rápido: Creación de una aplicación de ASP.NET en C#](https://docs.microsoft.com/es-es/azure/app-service/app-service-web-get-started-dotnet-framework#feedback)
* Content Source: [articles/app-service/app-service-web-get-started-dotnet-framework.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/app-service/app-service-web-get-started-dotnet-framework.md)

**Comment by srvbpigh** [comment]
Hello, @aitormartinezvalderrama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47067](https://github.com/MicrosoftDocs/azure-docs/issues/47067) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @aitormartinezvalderrama, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47067. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
