### ISSUE TITLE
Picture missing

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/azure-docs.es-es#701]
The Markdown suggests this picture is missing

!Synchronization Rules Editor](media/how-to-connect-fix-default-rules/default3a.png) 

the picture is also not present in the en-us version of this doc

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 68820b27-5fc7-cef8-156a-ea9fe37dc0b1
* Version Independent ID: a779a83e-b6d6-a51c-fc95-e2fea9b3f18c
* Content: [Procedimiento para corregir reglas predeterminadas modificadas - Azure AD Connect](https://docs.microsoft.com/es-es/azure/active-directory/hybrid/how-to-connect-fix-default-rules?source=docs#feedback)
* Content Source: [articles/active-directory/hybrid/how-to-connect-fix-default-rules.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/active-directory/hybrid/how-to-connect-fix-default-rules.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @AlexCesarini
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49860](https://github.com/MicrosoftDocs/azure-docs/issues/49860) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @AlexCesarini, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/49860. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
