### ISSUE TITLE
DNS Label example

### ISSUE THREAD

**Issue by jmorcar** [MicrosoftDocs/azure-docs.es-es#704]
If were possible, I need an example with dns label on a internal loadbalancer. I see this example:
 annotations:
    service.beta.kubernetes.io/azure-dns-label-name: myserviceuniquelabel

But, the example I think is for public loadbalancer , while I need internal dns label .local service like: 
&lt;miDNSLabel&gt;svc.cluster.local or &lt;miDnsLabel&gt;.&lt;namespace&gt;.svc.cluster.local 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 25afcc19-0998-3583-f6d8-e2a619c0e071
* Version Independent ID: 7629191a-6b3b-fb22-8b70-fa84fd785f38
* Content: [Creación de un equilibrador de carga interno de Azure Kubernetes Service (AKS)](https://docs.microsoft.com/es-es/azure/aks/internal-lb)
* Content Source: [articles/aks/internal-lb.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/aks/internal-lb.md)

**Comment by srvbpigh** [comment]
Hello, @jmorcar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50357](https://github.com/MicrosoftDocs/azure-docs/issues/50357) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @jmorcar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50357. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
