### ISSUE TITLE
Update az commands

### ISSUE THREAD

**Issue by adiazcan** [MicrosoftDocs/azure-docs.es-es#723]
This page refer to how to create a cluster with version 4 but the az commands refer to version 3. You have to change az openshift for az aro because az aro is the new extension for version 4

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 93aa980e-1970-235c-228a-7b19880171b8
* Version Independent ID: 6f7937a4-12e0-d61c-3bd8-c6347ec48385
* Content: [Tutorial: Creación de un clúster de Red Hat OpenShift en Azure](https://docs.microsoft.com/es-es/azure/openshift/tutorial-create-cluster#feedback)
* Content Source: [articles/openshift/tutorial-create-cluster.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/openshift/tutorial-create-cluster.md)
* Service: **container-service**
* GitHub Login: @jimzim
* Microsoft Alias: **jzim**

**Comment by srvbpigh** [comment]
Hello, @adiazcan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @adiazcan , 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

**URL**
  
Kind regards, 

Microsoft DOCS International Team

**Comment by adiazcan** [comment]
Hi, 

this docs is a tutorial for creating an OpenShift 4 cluster on Azure but the commands are for the previous version OpenShift 3. 

For example:

"az openshift create" is the command to create a cluster on version 3 and it doesn't work on version 4. 

I think yo change the title for the document to include version 4 but the all the commands are for version 3.

If you prefer, I can try to write the correct commands and send you a pull request.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55903](https://github.com/MicrosoftDocs/azure-docs/issues/55903) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @adiazcan, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55903. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
